# Generated by Django 4.0.5 on 2022-09-09 12:18

import acount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=acount.models.Product.nameFile),
        ),
    ]
